config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    redirect_to @task if @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task if @task.save
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
        <%= f.text_field :title, placeholder: 'Task title' %>
        <%= f.text_area :details, placeholder: 'Task details' %>
        <%= f.check_box :completed, placeholder: 'Task title' %>
        <%= f.submit class: 'btn btn-primary w-100' %>
      <% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2> <%= check_box "task", "completed", {:checked => task.completed, :disabled => true}%>
       <%= link_to task.title, task %></h2>
       <%= link_to 'Delete', task_path(task), method: :delete %>
<% end %>
<%= link_to 'new', new_task_path  %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed == true %>
  <p> <%= check_box "task", "completed" %> This task is completed </p>
<% else %>
  <p> <%= check_box "task", "completed" %> This task is not completed yet</p>
<% end %>

<%= link_to 'Back to list', tasks_path  %>
<%= link_to 'edit', edit_path  %>